import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Local Assistant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=''>
        <p className='text-center text-4xl my-4 font-bold'>Assistant</p>
        <div className='grid grid-cols-1 md:grid-cols-2 gap-1 my-4 max-w-6xl mx-auto'>
          <div className='btn'>
            <Link href='/check-in'><a className='p-2 bg-white rounded-md'>Check In</a></Link>
          </div>
          <div className='btn'>
            <Link href='/find-location'><a className='p-2 bg-white rounded-md'>Find Location</a></Link>
          </div>
          <div className='btn'>
            <Link href='/weather'><a className='p-2 bg-white rounded-md'>Weather</a></Link>
          </div>
          <div className='btn'>
            <Link href='/anyhting'><a className='p-2 bg-white rounded-md'>Anything</a></Link>
          </div>
        </div>
      </main>
    </div>
  )
}
